'use strict';

function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function shell(title,sub,body,script=''){
return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{box-sizing:border-box}html,body{margin:0;background:transparent;font-family:Arial,sans-serif}body{padding:6px;background:radial-gradient(circle at 50% 0%,#173047,#05080d 72%);color:#eff8ff}.card{padding:14px;border:2px solid #6ee7ff;border-radius:20px;background:linear-gradient(145deg,#081b2b,#102f43 55%,#050b12);box-shadow:inset 0 0 0 3px #123b50,0 8px 20px #000b}.title{text-align:center;color:#dff8ff;font:bold 23px Arial Black,Arial,sans-serif;letter-spacing:2px;text-shadow:0 0 12px #38bdf8}.sub{text-align:center;margin:3px 0 10px;color:#86b8ce;font:10px monospace;letter-spacing:1px}.hud{display:flex;justify-content:space-between;gap:6px;padding:8px;margin:8px 0;border:1px solid #5ee8ff66;border-radius:9px;background:#020a11;color:#a8c5d5;font:10px monospace}.hud b{color:#6ee7ff}.box{padding:12px;border:1px solid #3f8eaa;border-radius:12px;background:#06131d;margin:8px 0}.q{font:bold 18px Arial,sans-serif;text-align:center;color:#fff;margin:4px 0 10px}.muted{text-align:center;color:#82aabd;font:10px monospace}.buttons{display:grid;gap:7px;margin-top:9px}.buttons button,.btn{width:100%;min-height:42px;border:1px solid #6ee7ff;border-radius:10px;background:linear-gradient(#123448,#071a28);color:#e9fbff;font-weight:800}.buttons button:active,.btn:active{transform:scale(.96)}.input{width:100%;height:42px;border:1px solid #6ee7ff;border-radius:10px;background:#020b12;color:#fff;padding:0 10px;font:15px monospace;text-align:center}.result{text-align:center;min-height:28px;margin-top:9px;color:#d9ffea;font:bold 13px monospace;white-space:pre-wrap}.grid{display:grid;gap:5px}.grid3{grid-template-columns:repeat(3,1fr)}.cell{aspect-ratio:1;display:grid;place-items:center;border:1px solid #4ca6bf;border-radius:8px;background:#092131;color:#fff;font:bold 24px Arial}.cell:active{transform:scale(.94)}.footer{text-align:center;margin-top:10px;color:#6f98aa;font:9px monospace}
</style></head><body><div class="card"><div class="title">${esc(title)}</div><div class="sub">${esc(sub)}</div>${body}<div class="footer">TOHID-AI · POWERED BY MR TOHID</div></div><script>${script}</script></body></html>`;
}
function diceBattle(){return shell('🎲 TOHID DICE BATTLE','ROLL TWO DICE · BEAT TOHID',`<div class="box"><div class="q">Ready?</div><div class="buttons"><button id="roll">🎲 ROLL DICE</button></div><div id="out" class="result">Tap ROLL to start.</div></div>`,`(function(){function r(){return 1+Math.floor(Math.random()*6)}document.getElementById('roll').onclick=function(){var a=r()+r(),b=r()+r(),s=a>b?100:a===b?25:5;document.getElementById('out').textContent='👤 YOU: '+a+'\\n🤖 TOHID: '+b+'\\n\\n'+(a>b?'🏆 YOU WIN!':a===b?'🤝 DRAW!':'💥 YOU LOSE!')+'\\n⭐ SCORE: '+s}})();`);}
function emojiGuess(q){return shell('🎭 TOHID EMOJI GUESS','GUESS THE MOVIE',`<div class="box"><div class="q" style="font-size:30px">${esc(q[0])}</div><input class="input" id="ans" placeholder="Your answer"><div class="buttons"><button id="check">CHECK ANSWER</button></div><div id="out" class="result"></div></div>`,`(function(){var answer=${JSON.stringify(q[1])};document.getElementById('check').onclick=function(){var v=document.getElementById('ans').value.trim().toLowerCase();document.getElementById('out').textContent=v===answer?'🎉 CORRECT! +150':'❌ TRY AGAIN';}})();`);}
function mathRush(q){return shell('🧮 TOHID MATH RUSH','SOLVE THE EQUATION',`<div class="box"><div class="q">${esc(q.question)}</div><input class="input" id="ans" type="number" inputmode="numeric" placeholder="Answer"><div class="buttons"><button id="check">⚡ SUBMIT</button></div><div id="out" class="result"></div></div>`,`(function(){var answer=${q.answer};document.getElementById('check').onclick=function(){var v=Number(document.getElementById('ans').value);document.getElementById('out').textContent=v===answer?'⚡ CORRECT! +120 XP':'❌ WRONG · Correct: '+answer;}})();`);}
function numberGuess(){return shell('🔢 TOHID NUMBER GUESS','FIND THE HIDDEN NUMBER · 1–20',`<div class="hud"><span>TRIES <b id="tries">0</b></span><span>RANGE <b>1–20</b></span></div><div class="box"><div class="q">I picked a number.</div><input class="input" id="ans" type="number" min="1" max="20" inputmode="numeric" placeholder="1–20"><div class="buttons"><button id="guess">🎯 GUESS</button><button id="new">NEW GAME</button></div><div id="out" class="result">Make your first guess.</div></div>`,`(function(){var n=1+Math.floor(Math.random()*20),tries=0,done=false;var out=document.getElementById('out'),tr=document.getElementById('tries');document.getElementById('guess').onclick=function(){if(done)return;var v=Number(document.getElementById('ans').value);if(!Number.isInteger(v)||v<1||v>20){out.textContent='❌ Enter 1–20';return}tries++;tr.textContent=tries;if(v===n){done=true;out.textContent='🎯 CORRECT!\\\\nNumber: '+n+' · Attempts: '+tries}else out.textContent=v<n?'⬆️ GO HIGHER':'⬇️ GO LOWER'};document.getElementById('new').onclick=function(){n=1+Math.floor(Math.random()*20);tries=0;done=false;tr.textContent='0';out.textContent='New number selected.'}})();`);}
function quiz(q){return shell('🧠 TOHID QUIZ','QUICK KNOWLEDGE CHALLENGE',`<div class="box"><div class="q">${esc(q[0])}</div><input class="input" id="ans" placeholder="Your answer"><div class="buttons"><button id="check">✅ SUBMIT ANSWER</button></div><div id="out" class="result"></div></div>`,`(function(){var answer=${JSON.stringify(q[1])};document.getElementById('check').onclick=function(){var v=document.getElementById('ans').value.trim().toLowerCase();document.getElementById('out').textContent=v===answer?'✅ CORRECT! +100 POINTS':'❌ WRONG · Answer: '+answer;}})();`);}
function rps(){return shell('✊ TOHID AI RPS','ROCK · PAPER · SCISSORS',`<div class="buttons"><button data-v="rock">✊ ROCK</button><button data-v="paper">✋ PAPER</button><button data-v="scissors">✌️ SCISSORS</button></div><div id="out" class="result">Choose your move.</div>`,`(function(){var c=['rock','paper','scissors'];document.querySelectorAll('[data-v]').forEach(function(b){b.onclick=function(){var a=b.dataset.v,d=c[Math.floor(Math.random()*3)],win=(a==='rock'&&d==='scissors')||(a==='paper'&&d==='rock')||(a==='scissors'&&d==='paper');document.getElementById('out').textContent='YOU: '+a.toUpperCase()+'\\\\nTOHID: '+d.toUpperCase()+'\\\\n\\\\n'+(a===d?'🤝 DRAW · 25':win?'🏆 YOU WIN · 100':'💥 YOU LOSE · 5');}})})();`);}
function truthOrDare(truths,dares){return shell('🎭 TOHID TRUTH OR DARE','CHOOSE YOUR CHALLENGE',`<div class="buttons"><button id="truth">🟦 TRUTH</button><button id="dare">🟥 DARE</button></div><div class="box"><div id="out" class="result">Pick one.</div></div>`,`(function(){var t=${JSON.stringify(truths)},d=${JSON.stringify(dares)},o=document.getElementById('out');document.getElementById('truth').onclick=function(){o.textContent='🟦 TRUTH\\\\n\\\\n'+t[Math.floor(Math.random()*t.length)]};document.getElementById('dare').onclick=function(){o.textContent='🟥 DARE\\\\n\\\\n'+d[Math.floor(Math.random()*d.length)]}})();`);}
function wyr(q){return shell('🎯 WOULD YOU RATHER','CHOOSE ONE OPTION',`<div class="box"><div class="q">Would you rather…?</div><div class="buttons"><button data-v="A">A. ${esc(q.a)}</button><button data-v="B">B. ${esc(q.b)}</button><button data-v="C">C. ${esc(q.c)}</button></div><div id="out" class="result">Choose A, B or C.</div></div>`,`(function(){document.querySelectorAll('[data-v]').forEach(function(b){b.onclick=function(){document.getElementById('out').textContent='🎭 You chose '+b.dataset.v+' · good choice!'}})})();`);}
function ttt(){return shell('❌⭕ TOHID TIC-TAC-TOE','LOCAL MATCH · YOU ARE X',`<div class="hud"><span>YOU <b>X</b></span><span>TOHID <b>O</b></span><span id="status">YOUR TURN</span></div><div id="board" class="grid grid3">${Array.from({length:9},(_,i)=>`<button class="cell" data-i="${i}"></button>`).join('')}</div><div class="buttons"><button id="restart">RESTART</button></div>`,`(function(){var b=Array(9).fill(''),turn='X',over=false,win=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]],s=document.getElementById('status');function w(m){return win.some(function(x){return b[x[0]]===m&&b[x[1]]===m&&b[x[2]]===m})}function draw(){document.querySelectorAll('[data-i]').forEach(function(x){x.textContent=b[Number(x.dataset.i)]});s.textContent=over?'GAME OVER':turn==='X'?'YOUR TURN':'TOHID TURN'}function bot(){if(over)return;var free=b.map(function(v,i){return v?null:i}).filter(function(v){return v!==null});if(!free.length)return;var i=free[Math.floor(Math.random()*free.length)];b[i]='O';if(w('O')){over=true;s.textContent='🤖 TOHID WINS'}else if(b.every(Boolean)){over=true;s.textContent='🤝 DRAW'}else turn='X';draw()}document.querySelectorAll('[data-i]').forEach(function(x){x.onclick=function(){var i=Number(x.dataset.i);if(over||turn!=='X'||b[i])return;b[i]='X';if(w('X')){over=true;s.textContent='🏆 YOU WIN'}else if(b.every(Boolean)){over=true;s.textContent='🤝 DRAW'}else{turn='O';draw();setTimeout(bot,250)}draw()}});document.getElementById('restart').onclick=function(){b=Array(9).fill('');turn='X';over=false;draw()};draw()})();`);}
function challenge(game){return shell('🎮 TOHID MULTIPLAYER','CHALLENGE ANOTHER PLAYER',`<div class="box"><div class="q">${esc(game||'ttt').toUpperCase()}</div><div class="muted">HTML lobby · multiplayer session still uses bot commands.</div><div class="buttons"><button>Challenge: .challenge ${esc(game||'ttt')} @user</button><button>Accept: .challenge accept &lt;session-id&gt;</button></div></div>`);}

module.exports={shell,diceBattle,emojiGuess,mathRush,numberGuess,quiz,rps,truthOrDare,wyr,ttt,challenge};