'use strict';

const { sendRichHtml } = require('../../utils/TohidGenai');

function gameHtml() {
  return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{box-sizing:border-box}body{margin:0;padding:8px;background:#071018;color:#eef;font-family:Arial,sans-serif}.card{padding:12px;border:2px solid #7dd3fc;border-radius:18px;background:linear-gradient(145deg,#0b2230,#102c3d);text-align:center}.title{font-size:24px;font-weight:900;letter-spacing:2px}.sub{font:10px monospace;color:#9cc;margin:5px}.board{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:10px auto;max-width:300px}.tile{aspect-ratio:1;display:grid;place-items:center;border-radius:9px;background:#173247;font:bold 20px monospace}.tile.hot{background:#38bdf8;color:#032030}.score{font:bold 13px monospace;margin:7px}.controls{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;max-width:240px;margin:auto}.controls button{height:42px;border:1px solid #7dd3fc;border-radius:9px;background:#0b2432;color:#e8f8ff;font-size:19px}.up{grid-column:2}.hint{margin-top:8px;font:9px monospace;color:#8fb4c8}</style></head><body><div class="card"><div class="title">🔢 TOHID 2048</div><div class="sub">MERGE THE NUMBERS</div><div class="score">SCORE: <span id="score">0</span> · BEST: <span id="best">0</span></div><div class="board" id="board"></div><div class="controls"><button class="up" id="up">▲</button><button id="left">◀</button><button id="down">▼</button><button id="right">▶</button></div><div class="hint">Use buttons or arrow keys · Reach 2048</div></div><script>
(function(){var b=document.getElementById('board'),sc=document.getElementById('score'),bestEl=document.getElementById('best'),a=[],score=0,best=0;try{best=Number(localStorage.tohid2048Best||0)}catch(e){}bestEl.textContent=best;
function reset(){a=Array(16).fill(0);score=0;add();add();draw()}function add(){var e=a.map(function(v,i){return v?null:i}).filter(function(v){return v!==null});if(e.length)a[e[Math.floor(Math.random()*e.length)]]=Math.random()<.9?2:4}
function draw(){b.innerHTML='';a.forEach(function(v){var d=document.createElement('div');d.className='tile'+(v>=128?' hot':'');d.textContent=v||'';b.appendChild(d)});sc.textContent=score}
function move(dir){var old=a.slice();var lines=[];if(dir==='left'||dir==='right'){for(var r=0;r<4;r++){var l=a.slice(r*4,r*4+4);if(dir==='right')l.reverse();lines.push(l)}}else{for(var c=0;c<4;c++){var l=[];for(var r=0;r<4;r++)l.push(a[r*4+c]);if(dir==='down')l.reverse();lines.push(l)}}
lines=lines.map(function(l){l=l.filter(Boolean);for(var i=0;i<l.length-1;i++)if(l[i]===l[i+1]){l[i]*=2;score+=l[i];l.splice(i+1,1)}while(l.length<4)l.push(0);return l});
if(dir==='left'||dir==='right'){lines.forEach(function(l,r){if(dir==='right')l.reverse();for(var c=0;c<4;c++)a[r*4+c]=l[c]})}else{lines.forEach(function(l,c){if(dir==='down')l.reverse();for(var r=0;r<4;r++)a[r*4+c]=l[r]})}
if(a.join(',')!==old.join(',')){add();if(score>best){best=score;try{localStorage.tohid2048Best=best}catch(e){}}draw()}}
function key(e){var k=e.key.replace('Arrow','').toLowerCase();if(['left','right','up','down'].indexOf(k)>=0){e.preventDefault();move(k)}}document.addEventListener('keydown',key);['up','down','left','right'].forEach(function(x){document.getElementById(x).onclick=function(){move(x)}});reset()})();
</script></body></html>`;
}
module.exports={name:'2048',aliases:['twenty48'],description:'Interactive HTML 2048 number merge game',category:'games',async execute({sock,msg,from,reply}){try{await sendRichHtml({sock,jid:from,quoted:msg,html:gameHtml()})}catch(e){console.error('[2048 GenAI]',e.message);await reply('❌ 2048 HTML could not open on this WhatsApp client.')}}};