'use strict';
const {rewardMultiplayer}=require('../../utils/TohidGameStats');
const {get,finish}=require('../../utils/TohidMultiplayer');
function render(b){return b.slice(0,3).map((v,i)=>v||i+1).join(' | ')+'\n'+b.slice(3,6).map((v,i)=>v||i+4).join(' | ')+'\n'+b.slice(6).map((v,i)=>v||i+7).join(' | ');}
module.exports={name:'ttt',aliases:['tictactoe'],description:'Tic-Tac-Toe — multiplayer or local board',category:'games',async execute({from,reply,pushName,args}){const sid=String(args?.[0]||''),session=get(sid);
if(session&&session.status==='active'&&session.game==='ttt'){const n=Number(args?.[1]);if(!Number.isInteger(n)||n<1||n>9)return reply('❌ Move must be 1-9.');session.board=session.board||Array(9).fill('');session.turn=session.turn||session.challengerJid;if(from!==session.challengerJid&&from!==session.opponentJid)return reply('❌ You are not a player in this match.');if(from!==session.turn)return reply('⏳ Not your turn.');if(session.board[n-1])return reply('❌ Position already used.');const mark=from===session.challengerJid?'X':'O';session.board[n-1]=mark;const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]],won=wins.some(([a,b,c])=>session.board[a]&&session.board[a]===session.board[b]&&session.board[a]===session.board[c]);
if(won){finish(session.id,from);rewardMultiplayer(session.challengerJid,session.challenger,true);rewardMultiplayer(session.opponentJid,session.opponentJid===from?session.challenger:session.opponentJid,false);return reply('❌⭕ TOHID AI TTT\n\n'+render(session.board)+'\n\n🏆 Winner: '+(from===session.challengerJid?'Challenger':'Opponent')+'\n🎁 Winner: +75 XP / +50 Coins\n🎮 Loser: +25 XP / +10 Coins');}
if(session.board.every(Boolean)){finish(session.id,'draw');return reply('🤝 TOHID AI TTT\n\n'+render(session.board)+'\n\nDraw!');}
session.turn=from===session.challengerJid?session.opponentJid:session.challengerJid;return reply('❌⭕ TOHID AI TTT\n\n'+render(session.board)+'\n\nTurn: '+(session.turn===session.challengerJid?'X':'O')+'\nMove: .ttt '+session.id+' <1-9>');}
return reply('❌⭕ TOHID AI TTT\n\nStart multiplayer: .challenge ttt @user\nThen: .ttt <session-id> <1-9>');}};
