const API=(localStorage.getItem("TOHID_WEB_API")||"").replace(/\/$/,"");
const app=document.getElementById("app"),toast=document.getElementById("toast");
const plans=[["7d","7 Days","$2"],["30d","30 Days","$5"],["90d","90 Days","$10"],["lifetime","Lifetime","$50"],["script","Bot Script","$100"]];
function notify(t){toast.textContent=t;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2600)}
async function api(path,options={}){if(!API)throw new Error("API URL is not configured yet.");const r=await fetch(API+path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d}
function home(){location.hash="";location.reload()}
function render(view){if(view==="home"||!view)return location.hash="",location.reload();if(view==="pair")return app.innerHTML=pair();if(view==="plans")return app.innerHTML=plansView();if(view==="dashboard")return dashboard();if(view==="payments")return payments();if(view==="stats")return stats();if(view==="tutorial")return app.innerHTML=tutorial()}
function shell(title,body){return '<section class="panel"><button class="ghost" onclick="home()">← Home</button><h2>'+title+'</h2>'+body+'</section>'}
function pair(){return shell("🔗 Pair WhatsApp",'<p class="muted">Enter the WhatsApp number exactly as you would for pairing. Premium access is checked by the backend.</p><div class="field"><label>WhatsApp number</label><input id="number" inputmode="numeric" placeholder="9178499xxxxxx"></div><div class="field"><label>Custom code (optional, 8 letters/numbers)</label><input id="custom" maxlength="8" placeholder="AB12CD34"></div><button class="primary" onclick="startPair()">Generate Pairing Code</button><div id="pairResult"></div>')}
async function startPair(){const number=document.getElementById("number").value.trim(),custom=document.getElementById("custom").value.trim(),box=document.getElementById("pairResult");box.innerHTML='<div class="status">⏳ Starting pairing…</div>';try{const d=await api("/api/pair",{method:"POST",body:JSON.stringify({number,customCode:custom||undefined})});box.innerHTML='<div class="status">🔐 Pairing code: <b style="font-size:24px">'+(d.code||"—")+'</b><br><span class="muted">Open WhatsApp → Linked Devices → Link a device → enter this code.</span></div>'}catch(e){box.innerHTML='<div class="status">❌ '+e.message+'</div>'}}
function plansView(){return shell("👑 Premium Plans",'<div class="plan-grid">'+plans.map(p=>'<div class="plan"><div class="muted">'+p[1]+'</div><div class="price">'+p[2]+'</div><button class="primary" style="margin-top:14px" onclick="buy(\''+p[0]+'\')">Buy</button></div>').join("")+'</div><div id="buyBox"></div>')}
async function buy(key){const b=document.getElementById("buyBox");b.innerHTML='<div class="status">⏳ Loading payment methods…</div>';try{const d=await api("/api/plans/"+key);b.innerHTML='<div class="status"><b>'+d.name+'</b> — '+d.price+'<div class="row" style="margin-top:12px"><button class="secondary" onclick="pay(\''+key+'\',\'upi\')">🇮🇳 UPI / QR</button><button class="secondary" onclick="pay(\''+key+'\',\'binance\')">🟡 Binance</button></div></div>'}catch(e){b.innerHTML='<div class="status">❌ '+e.message+'</div>'}}
async function pay(key,method){try{const d=await api("/api/payment",{method:"POST",body:JSON.stringify({planKey:key,method})});document.getElementById("buyBox").innerHTML='<div class="status">💳 Payment request <b>'+d.paymentId+'</b><br><span class="muted">'+(d.instructions||"Follow the payment instructions returned by the backend.")+'</span><div class="field"><label>Transaction ID / UTR</label><input id="tx" placeholder="Enter transaction ID"></div><button class="primary" onclick="submitProof(\''+d.paymentId+'\')">Submit Payment Proof</button></div>'}catch(e){notify(e.message)}}
async function submitProof(id){try{const tx=document.getElementById("tx").value.trim();await api("/api/payment/"+id+"/proof",{method:"POST",body:JSON.stringify({transactionId:tx})});notify("Payment proof submitted")}catch(e){notify(e.message)}}
async function dashboard(){app.innerHTML=shell("📊 Dashboard",'<div class="status">⏳ Loading…</div>');try{const d=await api("/api/account");app.innerHTML=shell("📊 Dashboard",'<div class="status"><b>Plan:</b> '+(d.plan||"—")+'<br><b>Expiry:</b> '+(d.expiry||"—")+'<br><b>Bots:</b> '+(d.activeBots||0)+'/'+(d.slotLimit||0)+'</div><div class="row" style="margin-top:14px"><button class="secondary" data-view="plans">👑 My Plan</button><button class="secondary" data-view="payments">📜 My Payments</button></div>')}catch(e){app.innerHTML=shell("📊 Dashboard",'<div class="status">ℹ️ '+e.message+'<br><span class="muted">Connect/authenticate the web panel before loading account data.</span></div>')}}
async function payments(){app.innerHTML=shell("💳 My Payments",'<div class="status">⏳ Loading…</div>');try{const d=await api("/api/payments");app.innerHTML=shell("💳 My Payments",'<div class="status">'+(d.payments?.length?d.payments.map(p=>'<div style="padding:10px 0;border-bottom:1px solid #242735"><b>'+p.id+'</b> · '+p.planName+' · $'+p.priceUsd+'<br><span class="muted">'+p.status+'</span></div>').join(""):"No payment history.")+'</div>')}catch(e){app.innerHTML=shell("💳 My Payments",'<div class="status">ℹ️ '+e.message+'</div>')}}
async function stats(){app.innerHTML=shell("📊 Bot Statistics",'<div class="status">⏳ Loading…</div>');try{const d=await api("/api/stats");app.innerHTML=shell("📊 Bot Statistics",'<div class="status">👥 Users: '+d.users+'<br>🔗 Sessions: '+d.sessions+'<br>📊 Connections: '+d.connections+'<br>📅 Today: '+d.dailyConnections+'<br>👑 Premium: '+d.premium+'</div>')}catch(e){app.innerHTML=shell("📊 Bot Statistics",'<div class="status">ℹ️ '+e.message+'</div>')}}
function tutorial(){return shell("📖 Tutorial",'<p class="muted">1. Enter your WhatsApp number in Pair.<br>2. Generate the pairing code.<br>3. WhatsApp → Settings → Linked Devices → Link a device.<br>4. Enter the code shown by the web panel.<br><br>The pairing code expires according to the bot configuration.</p><button class="primary" data-view="pair">🔗 Pair Now</button>')}
document.addEventListener("click",e=>{const v=e.target.closest("[data-view]")?.dataset.view;if(v)render(v)});
window.addEventListener("hashchange",()=>render(location.hash.slice(1)));
render(location.hash.slice(1));